from snakemake.utils import min_version
import sys

min_version("8.0.0")

shell.prefix("set -euo pipefail")


report: "report/workflow.rst"


##### Target rules #####


include: "rules/init.smk"
include: "rules/io.smk"
include: "rules/tool_runner.smk"
include: "rules/analyze_results.smk"


## WILDCARDS CONSTRAINS
wildcard_constraints:
    sample=r"[a-zA-Z0-9_-]+",
    batch=r"[a-zA-Z0-9_-]+",


rule all:
    input:
        fn_callmemobile_allout()
