########################
# SNAKEMAKE PARAMETERS #
########################

# (1) Directories for individual stages of the workflow
input_dir:                input
intermediate_dir:         intermediate
output_dir:               output
conda_dir:                .conda

# (2) Parameters for Snakemake execution
use_conda:                True # build conda environments automatically by Snakemake

# (3) Path to databases
bakta_db:                 /n/data1/hms/dbmi/baym/databases/bakta_dbv5/db 
pvog_db:                  ./pvog_db

threads:                  24

##############
# PARAMETERS #
##############
prophage_maxdist:         5000
integron_pctolap:         0.95
mobileelement_maxdist:    10000
plasmidfinder_mincov:     0.6
plasmidfinder_threshold:  0.9

