name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Testing:
    runs-on: ${{ matrix.os }}

    continue-on-error:  false

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ 3.11, 3.12 ]
        snakemake-version: [ 8 ]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "latest"
          environment-name: test-env
          condarc: |
            channels:
              - conda-forge
              - bioconda
              - defaults
          create-args: >-
            python=${{ matrix.python-version }}
            snakemake
            mamba
            make
          init-shell: bash
          cache-environment: true
          post-cleanup: all
      - name: Versions
        shell: bash -el {0}
        run: |
          micromamba activate test-env
          python -v
          snakemake -v
      - name: Test workflow (local test data)
        shell: bash -el {0}
        run: |
          micromamba activate test-env
          make format
